name: space_cadet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flame: ^1.38.2
  flutter:
    sdk: flutter
  flutter_soloud: ^5.1.5
  forge2d: ^0.15.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flame_test: ^2.3.1
  image: ^4.10.1

flutter:
  uses-material-design: true

  assets:
    - assets/original/
    - assets/original/hd/
