// Writes docs/ELEMENT_MAP.md: every gameplay component of the table with
// its position in table space and its sprite rectangle in screen space,
// generated from PINBALL.DAT.
//
//   dart run tool/element_map.dart [path/to/PINBALL.DAT]
// ignore_for_file: avoid_print
import 'dart:io';

import 'package:space_cadet/dat/pinball_data.dart';

void main(List<String> args) {
  final path = args.isEmpty ? 'original/PINBALL.DAT' : args.first;
  final data = PinballData.parse(File(path).readAsBytesSync());
  final (ox, oy) = data.spriteOffset;
  final out = StringBuffer()
    ..writeln('# Element map')
    ..writeln()
    ..writeln('Generated by `dart run tool/element_map.dart` from the original')
    ..writeln('PINBALL.DAT. Do not edit by hand.')
    ..writeln()
    ..writeln('- **Table space**: x −8…8, y −14…15. +x is screen left, +y is')
    ..writeln(
      '  towards the drain. Gravity (${_f(data.gravity.$1)}, '
      '${_f(data.gravity.$2)}), ball radius ${_f(data.ballRadius)}.',
    )
    ..writeln('- **Screen**: sprite rectangle on the 600 × 416 screen, after')
    ..writeln('  subtracting the table offset ($ox, $oy).')
    ..writeln(
      '- **Layer**: collision mask; 1 = playfield, 2 and 4 = raised levels.',
    )
    ..writeln(
      '- Lights, light groups and sounds are left out (${data.components.where(_skip).length} entries).',
    )
    ..writeln()
    ..writeln(
      '| Type | Name | States | Table position | Walls | Screen sprite | Elasticity | Smoothness | Kicker | Layer |',
    )
    ..writeln('|---|---|---|---|---|---|---|---|---|---|');
  for (final c in data.components.where((c) => !_skip(c))) {
    final s = c.states.first;
    final b = s.bitmap;
    final pos = _centre(s.walls);
    out.writeln(
      '| ${c.type.name} | ${c.name ?? '#${c.group}'} | ${c.states.length} '
      '| ${pos == null ? '' : '(${_f(pos.$1)}, ${_f(pos.$2)})'} '
      '| ${s.walls.map(_wall).join(', ')} '
      '| ${b == null ? '' : '${b.width}×${b.height} at (${b.x - ox}, ${b.y - oy})'} '
      '| ${_f(s.material.elasticity)} | ${_f(s.material.smoothness)} '
      '| ${s.kicker.boost == 0 ? '' : 'boost ${_f(s.kicker.boost)}, threshold ${_f(s.kicker.threshold)}'} '
      '| ${s.collisionMask} |',
    );
  }
  File('docs/ELEMENT_MAP.md').writeAsStringSync(out.toString());
  print('Wrote docs/ELEMENT_MAP.md');
}

bool _skip(Component c) => const {
  ComponentType.light,
  ComponentType.lightGroup,
  ComponentType.lightBargraph,
  ComponentType.sound,
}.contains(c.type);

String _f(double v) => v.toStringAsFixed(2);

String _wall(WallShape w) => switch (w) {
  WallCircle(:final radius) => 'circle r${_f(radius)}',
  WallLine() => 'line',
  WallPolygon() => 'polygon ${w.length}',
};

(double, double)? _centre(List<WallShape> walls) {
  var (sx, sy, n) = (0.0, 0.0, 0);
  for (final w in walls) {
    final pts = switch (w) {
      WallCircle(:final x, :final y) => [x, y],
      WallLine(:final x1, :final y1, :final x2, :final y2) => [x1, y1, x2, y2],
      WallPolygon(:final points) => points,
    };
    for (var i = 0; i < pts.length; i += 2) {
      sx += pts[i];
      sy += pts[i + 1];
      n++;
    }
  }
  return n == 0 ? null : (sx / n, sy / n);
}
